<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить этот элемент?',
    'Cities' => 'Города',
    'City' => 'Город',
    'City Total' => 'Городов Всего',
    'Comment' => 'Коментарий',
    'Create' => 'Создать',
    'Create Region' => 'Создать регион',
    'Create Site' => 'Создать город',
    'Create Survey' => '@@Создать анкету@@',
    'Created At' => 'Создан',
    'Delete' => 'Удалить',
    'Demo Password: {password}' => 'Демо пароль {password}',
    'Demo Username: {name}' => 'Демо пользователь {name}',
    'Email' => 'Email',
    'Female' => 'Женский',
    'Gender' => 'Пол',
    'Home' => 'Главная',
    'Home Page' => 'Домашняя страница',
    'ID' => 'ИД',
    'Incorrect value' => 'Некоректное значение',
    'Male' => 'Мужской',
    'Name' => 'Имя',
    'Password' => 'Пароль',
    'Phone' => 'Телефон',
    'Rating' => 'Оценка',
    'Region' => 'Регион',
    'Regions' => 'Регионы',
    'Regions Total' => 'Регионов Всего',
    'Remember Me' => 'Запомнить меня',
    'Reset' => 'Сбросить',
    'Save' => 'Сохранить',
    'Search' => 'Поиск',
    'Select...' => 'Выбирете...',
    'Send' => 'Отправить',
    'Sign in to start your session' => 'Войдите, чтобы начать сеанс',
    'Survey Total' => 'Анкет всего',
    'Surveys' => 'Анкеты',
    'The requested page does not exist.' => 'Страницы не существует',
    'Update' => 'Редактировать',
    'Update City: {name}' => 'Редактировать город: {name}',
    'Update Region: {name}' => 'Редактирование региона: {name}',
    'Update Survey: {name}' => '@@Редактирование анкеты: {name}@@',
    'Updated At' => 'Обновлен',
    'Username' => 'Имя пользователя',
    'Порекомендовали бы ли вы нас?' => '',
];
